[tool.poetry]
name = "goitdshw03"
version = "0.1.0"
description = ""
authors = ["Anton Asieiev <ntn.kiev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scrapy = "^2.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
